In [2]:
import torch
import numpy as np

**데이터로부터 직접 생성하기**

데이터로부터 직접 텐서를 생성할 수 있다. 데이터의 자료형(data type은 자동으로 유추합니다.

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**다른 텐서로부터 생성하기**:

명시적으로 override하지 않는다면, 인자로 주어진 텐서의 속성(shape, datatype)을 유지합니다.

In [6]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensor: \n{x_rand}\n")

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])

Random Tensor: 
tensor([[0.9564, 0.6497],
        [0.7934, 0.1593]])



**무작위(random) 또는 상수(constant) 값을 사용하기**:

shape은 텐서의 차원을 나타내는 tuple로, 아래 함수들에서는 출력 텐서의 차원을 결정합니다.


In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n{rand_tensor}\n")
print(f"Ones Tensor: \n{ones_tensor}\n")
print(f"Zeros Tensor: \n{zeros_tensor}\n")

Random Tensor: 
tensor([[0.9403, 0.0323, 0.5095],
        [0.9114, 0.2566, 0.9991]])

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



# 텐서의 속성 (Attribute)

텐서의 속성은 텐서의 모양, 자료형 및 어느 장치에 저장되는지를 나타냅니다.

In [8]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# 텐서 연산
전치(transpose), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링 등 100가지 이상의 텐서 연산들을 [여기](https://pytorch.org/docs/stable/torch.html) 에서 확인 할 수 있습니다.

각 연산들은 일반적으로 CPU보다 빠른 GPU에서 실행할 수 있습니다.


In [9]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [12]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[...,-1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**텐서 합치기** torch.cat 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있습니다.


In [16]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**산술 연산(Arithmetic operations)**

In [18]:
#두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
# tensor.T 는 텐서의 전치(transpose)를 반환합니다.
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out = y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])